[versions]
activity = "1.12.3"
androidxArchCore = "2.2.0"
androidxTestCore = "1.7.0"
androidxTestExt = "1.3.0"
androidxTestJunitOld = "1.3.0"
androidxTestRules = "1.7.0"
androidxTestRunner = "1.7.0"
appcompat = "1.7.1"
binaryCompatibility = "0.18.1"
chucker = "4.3.0"
collar = "2.0.0"
core = "1.17.0"
coroutines = "1.10.2"
crypto = "1.1.0"
dbinspector = "5.4.9"
design = "1.13.0"
detekt = "1.23.8"
dokka = "2.1.0"
dynamicanimation = "1.1.0"
espresso = "3.7.0"
fragment = "1.8.9"
fragmentTest = "1.8.9"
gradle = "8.13.2"
inject = "0.9.0"
json = "1.10.0"
junit = "4.13.2"
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
ktlint = "1.8.0"
ktlintplugin = "14.0.1"
leakcanary = "2.14"
lifecycle = "2.10.0"
preference = "1.2.1"
recycler = "1.4.0"
robolectricShadow = "4.16.1"
room = "2.8.4"
roomTest = "2.8.4"
sentinel = "1.5.1"
startup = "1.2.0"
timber = "5.0.1"
workmanager = "2.11.1"

[libraries]
library = { module = "com.infinum.sentinel:sentinel", version.ref = "sentinel" }
librarynoop = { module = "com.infinum.sentinel:sentinel-no-op", version.ref = "sentinel" }
toolchucker = { module = "com.infinum.sentinel:tool-chucker", version.ref = "sentinel" }
toolcollar = { module = "com.infinum.sentinel:tool-collar", version.ref = "sentinel" }
tooldbinspector = { module = "com.infinum.sentinel:tool-dbinspector", version.ref = "sentinel" }
toolleakcanary = { module = "com.infinum.sentinel:tool-leakcanary", version.ref = "sentinel" }
toolappgallery = { module = "com.infinum.sentinel:tool-appgallery", version.ref = "sentinel" }
toolgoogleplay = { module = "com.infinum.sentinel:tool-googleplay", version.ref = "sentinel" }
tooltimber = { module = "com.infinum.sentinel:tool-timber", version.ref = "sentinel" }

tools-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-recycler = { module = "androidx.recyclerview:recyclerview", version.ref = "recycler" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-crypto = { module = "androidx.security:security-crypto", version.ref = "crypto" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomTest" }
androidx-workmanager-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidxArchCore" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidxTestCore" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-ext-junit-old = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunitOld" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragmentTest" }
androidx-crypto-alpha = { module = "androidx.security:security-crypto", version.ref = "crypto" }

material = { module = "com.google.android.material:material", version.ref = "design" }

inject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "inject" }
inject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "inject" }

detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintplugin" }

dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }

collar = { module = "com.infinum.collar:collar-ui", version.ref = "collar" }

dbinspector = { module = "com.infinum.dbinspector:dbinspector", version.ref = "dbinspector" }

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

junit = { module = "junit:junit", version.ref = "junit" }

robolectric-shadowapi = { module = "org.robolectric:shadowapi", version.ref = "robolectricShadow" }

[bundles]
androidx = [
    "androidx-core",
    "androidx-appcompat",
    "androidx-activity",
    "androidx-fragment",
    "androidx-recycler",
    "androidx-lifecycle-runtime",
    "androidx-lifecycle-viewmodel",
    "androidx-lifecycle-livedata",
    "androidx-lifecycle-process",
    "androidx-preference",
    "androidx-crypto",
    "androidx-startup",
    "androidx-dynamicanimation",
    "androidx-room-runtime",
    "androidx-room-ktx",
    "androidx-workmanager-ktx"
]
tools = [
    "toolchucker",
    "toolcollar",
    "tooldbinspector",
    "toolleakcanary",
    "toolappgallery",
    "toolgoogleplay",
    "tooltimber"
]

[plugins]
kotlin-binary-compatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibility" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }