[versions]
sentinel = "1.5.1"
gradle = "8.13.2"
kotlin = "1.9.22"
coroutines = "1.8.0"
json = "1.5.1"
core = "1.12.0"
appcompat = "1.6.1"
activity = "1.8.2"
fragment = "1.6.2"
recycler = "1.3.2"
lifecycle = "2.7.0"
preference = "1.2.1"
room = "2.6.1"
workmanager = "2.9.0"
startup = "1.1.1"
crypto = "1.1.0-alpha06"
dynamicanimation = "1.0.0"
design = "1.11.0"
inject = "0.6.1"
timber = "5.0.1"
detekt = "1.23.0"
ktlintplugin = "11.3.1"
ktlint = "0.45.2"
cpd = "3.3"
dokka = "1.8.10"
chucker = "4.1.0"
collar = "1.4.0"
dbinspector = "5.4.9"
leakcanary = "2.11"
thimble = "1.0.1"
binaryCompatibility = "0.17.0"

[libraries]
library = { module = "com.infinum.sentinel:sentinel", version.ref = "sentinel" }
librarynoop = { module = "com.infinum.sentinel:sentinel-no-op", version.ref = "sentinel" }
toolchucker = { module = "com.infinum.sentinel:tool-chucker", version.ref = "sentinel" }
toolcollar = { module = "com.infinum.sentinel:tool-collar", version.ref = "sentinel" }
tooldbinspector = { module = "com.infinum.sentinel:tool-dbinspector", version.ref = "sentinel" }
toolleakcanary = { module = "com.infinum.sentinel:tool-leakcanary", version.ref = "sentinel" }
toolappgallery = { module = "com.infinum.sentinel:tool-appgallery", version.ref = "sentinel" }
toolgoogleplay = { module = "com.infinum.sentinel:tool-googleplay", version.ref = "sentinel" }
toolthimble = { module = "com.infinum.sentinel:tool-thimble", version.ref = "sentinel" }
tooltimber = { module = "com.infinum.sentinel:tool-timber", version.ref = "sentinel" }

tools-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-recycler = { module = "androidx.recyclerview:recyclerview", version.ref = "recycler" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-crypto = { module = "androidx.security:security-crypto", version.ref = "crypto" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-workmanager-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager" }

material = { module = "com.google.android.material:material", version.ref = "design" }

inject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "inject" }
inject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "inject" }

detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintplugin" }

cpd = { module = "de.aaschmid:gradle-cpd-plugin", version.ref = "cpd" }

dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }

collar = { module = "com.infinum.collar:collar-ui", version.ref = "collar" }

dbinspector = { module = "com.infinum.dbinspector:dbinspector", version.ref = "dbinspector" }

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

thimble = { module = "com.infinum.thimble:thimble", version.ref = "thimble" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]
androidx = [
    "androidx-core",
    "androidx-appcompat",
    "androidx-activity",
    "androidx-fragment",
    "androidx-recycler",
    "androidx-lifecycle-runtime",
    "androidx-lifecycle-viewmodel",
    "androidx-lifecycle-livedata",
    "androidx-lifecycle-process",
    "androidx-preference",
    "androidx-crypto",
    "androidx-startup",
    "androidx-dynamicanimation",
    "androidx-room-runtime",
    "androidx-room-ktx",
    "androidx-workmanager-ktx"
]
tools = [
    "toolchucker",
    "toolcollar",
    "tooldbinspector",
    "toolleakcanary",
    "toolappgallery",
    "toolgoogleplay",
    "toolthimble",
    "tooltimber"
]

[plugins]
kotlin-binary-compatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibility" }